name: exchange_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.4.1
  intl: ^0.19.0
  fl_chart: ^0.70.2  # Добавляем зависимость для круговой диаграммы
  shared_preferences: ^2.2.0
  
  # PDF export dependencies
  pdf: ^3.10.7
  path_provider: ^2.1.1
  open_file: ^3.3.2
  permission_handler: ^11.0.0  # Add this for storage permissions
  
  cupertino_icons: ^1.0.8
  universal_html: ^2.0.4  # Add this for better web support

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true